### ISSUE TITLE
Translation Syntax Error

### ISSUE THREAD

**Issue by luke-** [humhub/tasks#143]
![image](https://user-images.githubusercontent.com/4736168/114519680-f0fec300-9c40-11eb-92fd-b8465d5640e4.png)

**Comment by yurabakhtin** [comment]
@luke- I fixed this in PR https://github.com/humhub/tasks/pull/144.

Maybe the fix looks strange but I found only this solution because during debugging I found the PHP library `intl` cannot create a constructor `$formatter = new \MessageFormatter($language, $pattern);` on the line 103 of the Yii file `protected/vendor/yiisoft/yii2/i18n/MessageFormatter.php`.

In debug I see `$language === null` and `$pattern === 'Show {0} more completed {0,plural,=1{task} other{tasks}}'`, and the constructor `\MessageFormatter()` can be initialised only when a parameter is used once in the string. In my opinion this is a bug of the PHP library `intl` because I guess the string worked in past.

My current `INTL_ICU_VERSION == 56.1` and `INTL_ICU_DATA_VERSION == 56.1`. Doc pages https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n#setup-environment

I didn't find similar issues in other places by regexp searching `Yii::t\(.+,plural`, so I think this bug was only in this module.

**Comment by luke-** [comment]
@yurabakhtin Thanks, seems to be a strange bug. I've also updated the existing messages accordingly: https://github.com/humhub/tasks/commit/06b8a1afc3c781fabec75ae62c51127eb88e645f
